#!/usr/bin/env python3

import numpy as np
from PIL import Image
import os


training_labels_file = "/Users/adesjarlais/devel/data/mnist/train-labels-idx1-ubyte"
training_images_file = "/Users/adesjarlais/devel/data/mnist/train-images-idx3-ubyte"

test_labels_file = "/Users/adesjarlais/devel/data/mnist/t10k-labels-idx1-ubyte"
test_images_file = "/Users/adesjarlais/devel/data/mnist/t10k-images-idx3-ubyte"


print("TEST SET: LABELS")
with open(test_labels_file, "r") as f1:
    header = np.fromfile(f1, dtype=np.dtype('>i4'), count=2)

    magic_number = header[0]
    item_count = header[1]

    print(f"\tmagic_number: {magic_number}")
    print(f"\titem_count: {item_count}")

    labels = np.fromfile(f1, dtype=np.ubyte, count=-1)

    print(f"\tlabels.size: {labels.size}")
    print(f"\tlabels: {labels}")

    f1.close()

print("\n\n\n\n\n")

print("TEST SET: IMAGES")
with open(test_images_file, "r") as f1:
    header = np.fromfile(f1, dtype=np.dtype('>i4'), count=4)

    magic_number = header[0]
    item_count = header[1]
    num_rows = header[2]
    num_columns = header[3]
    pixels_per_image = num_rows * num_columns

    print(f"\tmagic_number: {magic_number}")
    print(f"\titem_count: {item_count}")
    print(f"\tnum_rows: {num_rows}")
    print(f"\tnum_columns: {num_columns}")
    print(f"\tpixels_per_image: {pixels_per_image}")

    images = np.fromfile(f1, dtype=np.ubyte, count=-1)

    print(f"\timages.size: {images.size/pixels_per_image}")
    print(f"\timages: {images}")

    f1.close()


    print("\n\n\n\n\n")


    image_index = 0
    while True:

        print(f"SHOWING IMAGE {image_index}")
        image_pixels_start = image_index * pixels_per_image
        image_pixels_end = image_pixels_start + pixels_per_image

        print(f"\timage_pixels_start: {image_pixels_start}")
        print(f"\timage_pixels_end: {image_pixels_end}")

        image = images[image_pixels_start : image_pixels_end]
        image_pixels = np.reshape(image, (num_rows, num_columns))

        img = Image.fromarray(image_pixels)
        img.show()

        input("Next image?")
        print("\n\n")

        image_index = image_index + 1
