#!/usr/bin/env python3

# Finds a linear regression model using the normal equation for the mnist date set.

import numpy as np
import torch
import time


######### SETTINGS #########
training_labels_file = "/Users/adesjarlais/devel/data/mnist/train-labels-idx1-ubyte"
training_images_file = "/Users/adesjarlais/devel/data/mnist/train-images-idx3-ubyte"

test_labels_file = "/Users/adesjarlais/devel/data/mnist/t10k-labels-idx1-ubyte"
test_images_file = "/Users/adesjarlais/devel/data/mnist/t10k-images-idx3-ubyte"

model_save_file = "/Users/adesjarlais/devel/data/models/writing_recognition/linear_regression/model.pt"
save_model = True
use_saved_model = False
############################



def get_labels_from_file(file):

    with open(file, "r") as f1:
        header = np.fromfile(f1, dtype=np.dtype('>i4'), count=2)

        magic_number = header[0]
        item_count = header[1]
        labels = np.fromfile(f1, dtype=np.ubyte, count=-1)

        f1.close()

        assert(magic_number == 2049)
        assert(labels.size == item_count)

        return labels

def get_images_from_file(file):
    with open(file, "r") as f1:
        header = np.fromfile(f1, dtype=np.dtype('>i4'), count=4)

        magic_number = header[0]
        item_count = header[1]
        num_rows = header[2]
        num_columns = header[3]
        pixels_per_image = num_rows * num_columns
        images_bytes = np.fromfile(f1, dtype=np.ubyte, count=-1)

        f1.close()

        assert(magic_number == 2051)
        assert(num_rows == 28)
        assert(num_columns == 28)
        assert(images_bytes.size == item_count * num_rows * num_columns)

        images = np.reshape(images_bytes, (item_count, num_rows * num_columns))

        return images

def conform_training_image(image):
    model_input = image * 1.0/255.0
    model_input = np.insert(model_input, 0, 1)

    return model_input

def get_conformed_images_from_file(file):
    images = get_images_from_file(file)

    model_inputs = np.zeros((images.shape[0], images.shape[1] + 1))
    for image_index in range(images.shape[0]):
        model_inputs[image_index] = conform_training_image(images[image_index])

    return model_inputs

def batch_inference(model_params, input, labels):
    input_count = input.shape[0]

    model_outputs = input * model_params
    model_outputs = torch.sum(model_outputs, 1)

    model_losses = model_outputs - labels
    model_loss = torch.mean(model_losses)

    model_loss_mses = torch.pow(model_losses, 2)
    model_loss_mse = torch.mean(model_loss_mses)

    classified_outputs = torch.clip(model_outputs, min=0, max=9)
    classified_outputs = torch.round(classified_outputs, decimals=0)

    correct_inferences = torch.eq(classified_outputs, labels)
    total_correct = torch.sum(correct_inferences)
    accuracy = total_correct/input_count

    return (model_losses, model_loss, model_loss_mse, accuracy)

def validate_model(model_params, training_inputs, training_labels, test_inputs, test_labels):
    training_losses, avg_training_loss, avg_training_mse, avg_training_accuracy = batch_inference(model_params, training_inputs, training_labels)
    test_losses, avg_test_loss, avg_test_mse, avg_test_accuracy = batch_inference(model_params, test_inputs, test_labels)

    print(f"TRAINING:\tLoss: {avg_training_mse:.2f}\t\t\tAccuracy: {avg_training_accuracy:.2f}")
    print(f"TEST:\t\tLoss: {avg_test_mse:.2f}\t\t\tAccuracy: {avg_test_accuracy:.2f}")
    print("")

    return training_losses

def save_model(model_params, output_file_path):
    torch.save(model_params, output_file_path)

def load_model(file_path):
    return torch.load(file_path)
    return np.loadtxt(file_path, dtype=float)



# Pull in training and test inputs and labels
training_labels = get_labels_from_file(training_labels_file)
training_images = get_conformed_images_from_file(training_images_file)

test_labels = get_labels_from_file(test_labels_file)
test_images = get_conformed_images_from_file(test_images_file)


pt_training_inputs = torch.from_numpy(training_images).float()
pt_training_labels = torch.from_numpy(training_labels)

pt_test_inputs = torch.from_numpy(test_images).float()
pt_test_labels = torch.from_numpy(test_labels)

device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

pt_training_inputs.to(device)
pt_training_labels.to(device)

pt_test_inputs.to(device)
pt_test_labels.to(device)


# Find the optimum model_params using the normal equation
start_time = time.time()

if use_saved_model:
    model_params = load_model(model_save_file)
else:
    training_inputs_transpose = torch.transpose(pt_training_inputs, 0, 1)

    model_params = torch.matmul(training_inputs_transpose, pt_training_inputs)
    model_params = torch.linalg.pinv(model_params)
    model_params = torch.matmul(model_params, training_inputs_transpose)
    model_params = torch.matmul(model_params, pt_training_labels.float())


validate_model(model_params, pt_training_inputs, pt_training_labels, pt_test_inputs, pt_test_labels)

if save_model:
    save_model(model_params, model_save_file)

# Print losses one last time
print("Complete.")
print("FINAL RESULTS:")

end_time = time.time()
print("Total execution time: {:.2f}".format(end_time - start_time))
